apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
 replicas: 3
 selector:
   matchLabels:
     app: php-app
 template:
   metadata:
     labels:
       app: php-app
   spec:                  
     containers:
     - name: php-app
       image: vigneshvicky12345/php-app:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 80
